version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    image: mdxd23/foodgram-project-react-backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: mdxd23/foodgram-project-react-frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build/build

  nginx:
    image: nginx:1.19.3
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8000:80
    depends_on:
      - backend